name = "mail_workers" # todo
main = "./dist/main.js"
compatibility_date = "2022-10-10"

[[d1_databases]]
binding = "DB"  
database_name = "mailworker"
database_id = "e2636b1d-7f72-4d66-bdb4-6c8ac92f8125"